### PR TITLE
Update regarding version that work

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
There's no need any longer to alarm users about 1.1+ with it now working.

You could even change this in a different way, and block 1.0.x. You probably know how. I'm conflicted if people should just be informed this way (they find out soon enough that 1.0 doesn't work) or blocking on install. And since I reported to Julia the segfault, you need to download for older, but I did show how for an old commit, so maybe not an argument for not blocking.

**Comment by PallHaraldsson** [comment]
"Jy2Jl". I keep writing it incorrectly... Usually Py2Cl... and looking at the screen why you package doesn't work. :) By now I know to look carefully at the error message and assume my mistake.

**Comment by thautwarm** [comment]
lol, what do you think of Py2CI stands for?

**Comment by PallHaraldsson** [comment]
Nothing, maybe my subconscious has some idea. I keep making this mistake.

**Pull request merged**
